Repository PoliNetworkOrg/TheTOLProject, pull requests merged in 2022-04, with the labels that each got.

#11 feat: mobile responsive design
  src/components/App.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/InfoView/InfoEnd.tsx
  src/components/QuestionsForm/AnswerForm.tsx
  src/components/QuestionsForm/QuestionHeader.tsx
  src/components/QuestionsForm/QuestionsForm.tsx
  src/components/QuestionsForm/RecapBar.tsx
  src/components/QuestionsForm/Timer.tsx
  src/components/QuestionsForm/TopControls.tsx
  src/utils/contexts.ts
Labels: type: feature

#23 fix: recap table getting cut on mobile
  src/components/InfoView/InfoEnd.tsx
Labels: type: fix

#22 feat: add way to start a new test from results
  src/components/App.tsx
  src/components/Footer.tsx
  src/components/InfoView/ExtendedCorrection/ExtendedCorrection.tsx
  src/components/InfoView/InfoEnd.tsx
Labels: type: feature

#27 fix: all links now replace history entries
  src/components/Footer.tsx
  src/components/InfoView/InfoView.tsx
  src/components/QuestionsForm/QuestionsForm.tsx
Labels: type: bug, type: fix

#28 release: v1.1.0
  README.md
  package-lock.json
  package.json
  public/index.html
  src/components/App.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/InfoView/ExtendedCorrection/ExtendedCorrection.tsx
  src/components/InfoView/InfoEnd.tsx
  src/components/InfoView/InfoView.tsx
  src/components/QuestionsForm/AnswerForm.tsx
  src/components/QuestionsForm/QuestionHeader.tsx
  src/components/QuestionsForm/QuestionsForm.tsx
  src/components/QuestionsForm/RecapBar.tsx
  src/components/QuestionsForm/Timer.tsx
  src/components/QuestionsForm/TopControls.tsx
  src/components/pages/About.tsx
  src/components/pages/QPreview.tsx
  src/utils/constants.ts
  src/utils/contexts.ts
Labels: type: chore
